baseURL =  "https://bibaijin.github.io/my-blog/"
languageCode = "zh"
title = "博客 | 金比白"
theme = "Hucore"
publishDir = "docs"
copyright = "&copy; 2017 | 金比白 ♥"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "金比白的博客"
keywords = ["blog"]
author = "金比白"
sharingicons = true
displayauthor = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/bibaijin"
fa_icon = "fa-github"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[params.font]
text = "Roboto"
code = "Roboto Mono"